import keyMirror from 'react/lib/keyMirror'

export default keyMirror({
    DISMISS_FLASH: null,
    SET_WORKCENTER_VALUE: null,
    RECEIVE_WORKCENTER_START: null, 
    RECEIVE_WORKCENTER_SUCCESS: null,
    RECEIVE_WORKCENTER_FAILED: null,
    CHOOSE_WORKCENTER: null,
    SET_NPORDER_INITIAL: null,
    RECEIVE_NPORDER_START: null,
    RECEIVE_NPORDER_SUCCESS: null,
    RECEIVE_NPORDER_FAILED: null,
    RECEIVE_NPCONF_SUCCESS: null,
    RECEIVE_NPCONF_FAILED: null,
    SAVE_CONFIRMATIONS_SUCCESS: null,
    SAVE_CONFIRMATIONS_FAILED: null
})
